# .NET MAUI Android
# Build, sign, and publish a .NET MAUI Android package.

trigger:
 - none 
#  branches:
#    include:
#    - main
#    - releases/*
#  paths:
#    include:
#    - docs
#    exclude:
#    - azure-pipelines-changelog.yml
#    - azure-pipelines.yml

pool:
  vmImage: 'windows-latest'

variables:
  - group: xamarin-android-aab
  - name: buildConfiguration
    value: 'Release'
  - name: outputDirectory
    value: '$(build.binariesDirectory)/$(buildConfiguration)'
  - name: BuildID
    value: '$(Build.BuildID)'
  - name: packageFormat
    value: aab
  - name: dotnetVersion
    value: '10.0.x'
  - name: targetFramework
    value: 'net10.0-android'
  - name: appProject
    value: 'AdbApp/AdbApp.csproj'

steps:
- checkout: self
  submodules: true

# set version variables because the predefined like $(Year:yy) can't be used in tasks 
- task: PowerShell@2
  name: setvariable
  displayName: 'setting variables MajorVersion, MinorVersion, DayOfMonth'
  inputs:
    targetType: 'inline'
    script: |
      $year=$(Get-Date -Format 'yy')
      Write-Host $year
      Write-Host "##vso[task.setvariable variable=MajorVersion]$year"
      $month=[datetime]::Today.Month.ToString('0') 
      Write-Host $month
      Write-Host "##vso[task.setvariable variable=MinorVersion]$month"
      $day=$(Get-Date -Format 'dd')
      Write-Host $day
      Write-Host "##vso[task.setvariable variable=DayOfMonth]$day"
      $version="$year.$month.$(BuildID).0"
      Write-Host $version
      Write-Host "##vso[task.setvariable variable=version]$version"

- task: UseDotNet@2
  displayName: 'Install .NET SDK $(dotnetVersion)'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'

- task: PowerShell@2
  displayName: 'Install MAUI Android workload'
  inputs:
    targetType: 'inline'
    script: |
      dotnet workload install maui-android --ignore-failed-sources

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(appProject)'

- task: DownloadSecureFile@1
  name: signingCert
  displayName: 'Download certificate'
  inputs:
   secureFile: 'get.keystore'

- task: DotNetCoreCLI@2
  displayName: 'Publish signed Android $(packageFormat)'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(appProject)'
    arguments: >
      -c $(buildConfiguration)
      -f $(targetFramework)
      /p:AndroidKeyStore=true
      /p:AndroidSigningKeyStore="$(signingCert.secureFilePath)"
      /p:AndroidSigningStorePass="$(keystore.password)"
      /p:AndroidSigningKeyAlias="$(key.alias)"
      /p:AndroidSigningKeyPass="$(key.password)"
      /p:AndroidPackageFormats=$(packageFormat)
      /p:ApplicationDisplayVersion=$(version)
      /p:ApplicationVersion=$(BuildID)
      /p:ContinuousIntegrationBuild=true

- task: 'CopyFiles@2'
  displayName: 'Copy deliverables'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/AdbApp/bin/$(buildConfiguration)/$(targetFramework)/publish'
    Contents: '*.$(packageFormat)'
    TargetFolder: 'drop'

- task: PublishBuildArtifacts@1
  displayName: 'Publish release'
  inputs:
    pathToPublish: 'drop'
    artifactName: 'release'

- task: GooglePlayReleaseBundle@3
  inputs:
    serviceConnection: 'googleplayconsole'
    applicationId: 'get.the.solution.AdbApp'
    bundleFile: '**/*-Signed.$(packageFormat)'
    track: 'production'
